version: "3.8"
services:
  treat_raw_data:
    build:
      context: ./treat_raw_data
    image: treat_raw_data
    networks:
      - jenkins_network
    volumes:
      - shared_data:/compartilhado

  train_model:
    build:
      context: ./train_model
    image: train_model
    networks:
      - jenkins_network
    volumes:
      - shared_data:/compartilhado

  app:
    build:
      context: ./app
    image: app
    networks:
      - jenkins_network
    volumes:
      - shared_data:/compartilhado

networks:
  jenkins_network:

volumes:
  shared_data:
